package se.alipsa.jmlx.ffi;

import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Loads {@code libmlxc.dylib} and installs mlx-c's error handler.
 *
 * <p>{@link #ensureLoaded()} is idempotent and caches its outcome, unlike a
 * static initializer: a static initializer gives {@code ExceptionInInitializerError}
 * on first touch and a bare {@code NoClassDefFoundError} with the cause discarded
 * on every subsequent touch (req/initial-plan.md §5) -- exactly what a confused
 * contributor would hit on their second test run. This caches the outcome and
 * rethrows the original cause every time instead.
 */
public final class NativeLoader {

    private NativeLoader() {}

    private static final Object LOCK = new Object();
    private static boolean loaded = false;
    private static RuntimeException loadFailure = null;

    private static final ThreadLocal<String> LAST_NATIVE_ERROR = new ThreadLocal<>();

    /**
     * Loads the native library and installs the error handler, if not already
     * done. Safe to call repeatedly and from multiple threads.
     */
    public static void ensureLoaded() {
        synchronized (LOCK) {
            if (loaded) {
                return;
            }
            if (loadFailure != null) {
                throw loadFailure;
            }
            try {
                doLoad();
                loaded = true;
            } catch (RuntimeException e) {
                loadFailure = e;
                throw e;
            }
        }
    }

    private static void doLoad() {
        Path dir = resolveLibraryDir();

        // req/initial-plan.md §5: validate before loading, or the failure
        // surfaces much later as an opaque error on the first GPU op and
        // reads like a bug in the op, not a missing file.
        Path metallib = dir.resolve("mlx.metallib");
        if (!Files.exists(metallib)) {
            throw new IllegalStateException(
                "mlx.metallib not found at " + metallib
                    + " -- run scripts/bootstrap-native.sh to stage the native runtime directory");
        }
        Path dylib = dir.resolve("libmlxc.dylib");
        if (!Files.exists(dylib)) {
            throw new IllegalStateException(
                "libmlxc.dylib not found at " + dylib
                    + " -- run scripts/bootstrap-native.sh to stage the native runtime directory");
        }

        // System.load (a full path), not SymbolLookup.libraryLookup:
        // req/initial-plan.md Decision 8. The bindings generated by
        // regen-bindings.sh (no -l flag) resolve symbols through
        // SymbolLookup.loaderLookup(), which only sees libraries registered
        // with the calling classloader -- exactly what System.load does, and
        // exactly what SymbolLookup.libraryLookup() does not.
        System.load(dylib.toString());

        installErrorHandler();
    }

    /**
     * Resolves the directory containing {@code libmlxc.dylib} and its
     * siblings. In order: the {@code jmlx.library.path} system property
     * (this is also how the Gradle build injects an absolute path -- see
     * root build.gradle and jmlx-examples/build.gradle), then the
     * {@code JMLX_LIBRARY_PATH} environment variable.
     */
    private static Path resolveLibraryDir() {
        String prop = System.getProperty("jmlx.library.path");
        if (prop != null && !prop.isBlank()) {
            return Path.of(prop);
        }
        String env = System.getenv("JMLX_LIBRARY_PATH");
        if (env != null && !env.isBlank()) {
            return Path.of(env);
        }
        throw new IllegalStateException(
            "native library directory not specified -- set the 'jmlx.library.path' system property"
                + " or the JMLX_LIBRARY_PATH environment variable to the directory produced by"
                + " scripts/bootstrap-native.sh (native/install/lib)");
    }

    // Kept alive for the process lifetime: the upcall stub must remain valid
    // for as long as mlx-c might call the error handler, which is the whole
    // process. Never closed.
    private static final Arena ERROR_HANDLER_ARENA = Arena.ofShared();

    /**
     * mlx-c's error convention is a checkable {@code int} status on every
     * call, but its default error handler calls {@code printf} then
     * {@code exit(-1)} (req/initial-plan.md, research findings) -- so on an
     * unmodified install, the process would exit before that status is ever
     * observed. Installing a handler that only records the message, and
     * does not exit, is what makes {@code check(...)} in jmlx-core viable at
     * all.
     */
    private static void installErrorHandler() {
        MemorySegment handlerStub =
            mlx_error_handler_func.allocate(NativeLoader::onNativeError, ERROR_HANDLER_ARENA);
        mlx_h.mlx_set_error_handler(handlerStub, MemorySegment.NULL, MemorySegment.NULL);
    }

    private static void onNativeError(MemorySegment msg, MemorySegment data) {
        LAST_NATIVE_ERROR.set(msg.reinterpret(Long.MAX_VALUE).getString(0));
    }

    /**
     * The message from the most recent native error observed on the calling
     * thread, or {@code null} if none has been observed (or it has been
     * cleared via {@link #clearLastNativeError()}).
     *
     * <p>mlx-c's error handler runs synchronously on the same thread that
     * made the failing call, so this is thread-local rather than shared --
     * see the thread-confinement contract on MLXScope/MLXArray.
     */
    public static String lastNativeError() {
        return LAST_NATIVE_ERROR.get();
    }

    /** Clears the calling thread's last-observed native error. */
    public static void clearLastNativeError() {
        LAST_NATIVE_ERROR.remove();
    }
}
