package se.alipsa.jmlx.ffi;

import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Optional;

/**
 * Loads {@code libmlxc.dylib} and installs mlx-c's error handler.
 *
 * <p>{@link #ensureLoaded()} is idempotent and caches its outcome, unlike a static initializer: a
 * static initializer gives {@code ExceptionInInitializerError} on first touch and a bare {@code
 * NoClassDefFoundError} with the cause discarded on every subsequent touch (req/initial-plan.md §5)
 * -- exactly what a confused contributor would hit on their second test run. This caches the
 * outcome and rethrows the original cause every time instead.
 */
public final class NativeLoader {

  private NativeLoader() {}

  private static final Object LOCK = new Object();
  private static boolean loaded = false;
  private static Throwable loadFailure = null;

  private static final ThreadLocal<String> LAST_NATIVE_ERROR = new ThreadLocal<>();

  /**
   * Loads the native library and installs the error handler, if not already done. Safe to call
   * repeatedly and from multiple threads.
   */
  public static void ensureLoaded() {
    synchronized (LOCK) {
      if (loaded) {
        return;
      }
      if (loadFailure != null) {
        if (loadFailure instanceof RuntimeException re) {
          throw re;
        }
        if (loadFailure instanceof Error err) {
          throw err;
        }
        // Unreachable today -- the catch below only ever assigns a
        // RuntimeException or LinkageError -- but loadFailure's declared
        // type is the wider Throwable, so nothing stops a future widening
        // of that catch from landing here. Failing loudly with the
        // original cause attached beats a raw ClassCastException silently
        // discarding it, which is exactly the failure mode this class
        // exists to avoid (see the class javadoc).
        throw new IllegalStateException("unexpected cached native load failure", loadFailure);
      }
      try {
        doLoad();
        loaded = true;
      } catch (RuntimeException | LinkageError e) {
        // System.load throws UnsatisfiedLinkError (a LinkageError) for a
        // present-but-unloadable dylib (wrong arch, missing @rpath sibling,
        // unresolved symbol) -- must be caught here too, or the caching
        // contract above doesn't hold for the most likely real failure.
        // A multi-hundred-MB extraction can fail transiently (ENOSPC, a temporarily unwritable
        // volume, or a network-mounted home directory). Let a direct loader caller retry that I/O
        // path; explicit configuration and actual System.load failures remain deterministic and
        // are cached. Static-initializer callers still fail normally on their first attempt.
        if (!(e instanceof ClasspathNativeExtractor.NativeExtractionException)) {
          loadFailure = e;
        }
        throw e;
      }
    }
  }

  private static void doLoad() {
    Path dir = resolveLibraryDir();

    // req/initial-plan.md §5: validate before loading, or the failure
    // surfaces much later as an opaque error on the first GPU op and
    // reads like a bug in the op, not a missing file.
    Path metallib = dir.resolve("mlx.metallib");
    if (!Files.exists(metallib)) {
      throw new IllegalStateException(
          "mlx.metallib not found at "
              + metallib
              + " -- run scripts/bootstrap-native.sh to stage the native runtime directory");
    }
    Path dylib = dir.resolve("libmlxc.dylib");
    if (!Files.exists(dylib)) {
      throw new IllegalStateException(
          "libmlxc.dylib not found at "
              + dylib
              + " -- run scripts/bootstrap-native.sh to stage the native runtime directory");
    }

    // System.load (a full path), not SymbolLookup.libraryLookup:
    // req/initial-plan.md Decision 8. The bindings generated by
    // regen-bindings.sh (no -l flag) resolve symbols through
    // SymbolLookup.loaderLookup(), which only sees libraries registered
    // with the calling classloader -- exactly what System.load does, and
    // exactly what SymbolLookup.libraryLookup() does not.
    System.load(dylib.toString());

    installErrorHandler();
  }

  /**
   * Resolves the directory containing {@code libmlxc.dylib} and its siblings. In order: the {@code
   * jmlx.library.path} system property (this is also how the Gradle build injects an absolute path
   * -- see root build.gradle and jmlx-examples/build.gradle), then the {@code JMLX_LIBRARY_PATH}
   * environment variable, then -- if neither is set and a {@code se.alipsa:jmlx-native-macos-arm64}
   * dependency is on the classpath -- {@link ClasspathNativeExtractor} extracting the bundled
   * binaries to a per-pin cache directory.
   */
  private static Path resolveLibraryDir() {
    String prop = System.getProperty("jmlx.library.path");
    if (prop != null && !prop.isBlank()) {
      return Path.of(prop);
    }
    String env = System.getenv("JMLX_LIBRARY_PATH");
    if (env != null && !env.isBlank()) {
      return Path.of(env);
    }
    if (ClasspathNativeExtractor.isSupportedPlatform()) {
      Optional<Path> extracted = ClasspathNativeExtractor.extractIfAvailable();
      if (extracted.isPresent()) {
        return extracted.get();
      }
    }
    throw new IllegalStateException(
        "native library directory not specified -- set the 'jmlx.library.path' system property"
            + " or the JMLX_LIBRARY_PATH environment variable to the directory produced by"
            + " scripts/bootstrap-native.sh (native/install/lib), or add a runtime dependency on"
            + " se.alipsa:jmlx-native-macos-arm64 so the bundled native libraries can be"
            + " extracted automatically"
            + (ClasspathNativeExtractor.isSupportedPlatform()
                ? ""
                : " (note: no published native artifact exists for your platform -- os.name="
                    + System.getProperty("os.name")
                    + ", os.arch="
                    + System.getProperty("os.arch")
                    + " -- only macOS/aarch64 is supported today)"));
  }

  // Kept alive for the process lifetime: the upcall stub must remain valid
  // for as long as mlx-c might call the error handler, which is the whole
  // process. Never closed.
  private static final Arena ERROR_HANDLER_ARENA = Arena.ofShared();

  /**
   * The mlx-c error convention is a checkable {@code int} status on every call, but its default
   * error handler calls {@code printf} then {@code exit(-1)} (req/initial-plan.md, research
   * findings) -- so on an unmodified install, the process would exit before that status is ever
   * observed. Installing a handler that only records the message, and does not exit, is what makes
   * {@code checked(...)} in jmlx-core viable at all.
   */
  private static void installErrorHandler() {
    MemorySegment handlerStub =
        mlx_error_handler_func.allocate(NativeLoader::onNativeError, ERROR_HANDLER_ARENA);
    mlx_h.mlx_set_error_handler(handlerStub, MemorySegment.NULL, MemorySegment.NULL);
  }

  // This runs as an upcall from native code: any Throwable escaping it is a
  // fatal JVM error, not a Java exception, so it must never let one through
  // -- a null msg (SIGSEGV via getString(0) at address 0) or invalid/
  // unterminated UTF-8 (getString throws) would otherwise crash the process
  // on exactly the path installed to replace mlx-c's own printf+exit(-1).
  private static void onNativeError(MemorySegment msg, MemorySegment data) {
    try {
      LAST_NATIVE_ERROR.set(
          msg.address() == 0
              ? "<null message from mlx-c>"
              : msg.reinterpret(Long.MAX_VALUE).getString(0));
    } catch (Throwable t) {
      LAST_NATIVE_ERROR.set("<unreadable message from mlx-c: " + t + ">");
    }
  }

  /**
   * The message from the most recent native error observed on the calling thread, or {@code null}
   * if none has been observed (or it has been cleared via {@link #clearLastNativeError()}).
   *
   * <p>The mlx-c error handler runs synchronously on the same thread that made the failing call, so
   * this is thread-local rather than shared -- see the thread-confinement contract on
   * MLXScope/MLXArray.
   *
   * @return the last observed native error message, or {@code null}
   */
  public static String lastNativeError() {
    return LAST_NATIVE_ERROR.get();
  }

  /** Clears the calling thread's last-observed native error. */
  public static void clearLastNativeError() {
    LAST_NATIVE_ERROR.remove();
  }
}
