package se.alipsa.jmlx.buildsrc;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Set;
import java.util.TreeSet;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/** Deterministically renders the initial inventory of the committed jextract MLX binding. */
public final class MlxApiInventory {

  private static final Pattern PIN = Pattern.compile("(?m)^([A-Z_]+)=\"([^\"]+)\"$");
  private static final Pattern METHOD =
      Pattern.compile("(?m)^    public static [^\\n(]+ (mlx_[a-z0-9_]+)\\(");

  private MlxApiInventory() {}

  /** Returns the complete checked-in inventory text for {@code repositoryRoot}. */
  public static String render(Path repositoryRoot) throws IOException {
    String bootstrap =
        Files.readString(
            repositoryRoot.resolve("scripts/bootstrap-native.sh"), StandardCharsets.UTF_8);
    String binding =
        Files.readString(
            repositoryRoot.resolve(
                "jmlx-ffi/src/main/generated/java/se/alipsa/jmlx/ffi/mlx_h.java"),
            StandardCharsets.UTF_8);
    Set<String> symbols = new TreeSet<>();
    Matcher matcher = METHOD.matcher(binding);
    while (matcher.find()) {
      symbols.add(matcher.group(1));
    }
    String metal = pin(bootstrap, "MLX_METAL_VERSION");
    StringBuilder out = new StringBuilder();
    out.append("# MLX API inventory\n\n");
    out.append("Generated by `./gradlew generateMlxApiInventory`; do not edit manually.\n\n");
    out.append("- mlx-metal: `").append(metal).append("`\n");
    String mlxc = pin(bootstrap, "MLX_C_COMMIT");
    out.append("- mlx-c: `").append(mlxc).append("`\n");
    out.append("- committed callable bindings: ").append(symbols.size()).append("\n\n");
    out.append(
        "Unmapped bindings are intentionally recorded as `unplanned`; a later explicit mapping\n");
    out.append("file controls public status and handwritten call-site authorization.\n\n");
    out.append("| Native symbol | Status | Facade | Tests |\n");
    out.append("| --- | --- | --- | --- |\n");
    for (String symbol : symbols) {
      out.append("| `").append(symbol).append("` | unplanned | — | — |\n");
    }
    return out.toString();
  }

  /** Writes the rendered inventory to {@code output}. */
  public static void write(Path repositoryRoot, Path output) throws IOException {
    Files.writeString(output, render(repositoryRoot), StandardCharsets.UTF_8);
  }

  private static String pin(String bootstrap, String name) {
    Matcher matcher = PIN.matcher(bootstrap);
    while (matcher.find()) {
      if (matcher.group(1).equals(name)) {
        return matcher.group(2);
      }
    }
    throw new IllegalArgumentException("scripts/bootstrap-native.sh does not define " + name);
  }
}
