package se.alipsa.jmlx.buildsrc;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.EnumMap;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import java.util.TreeSet;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Stream;

/** Deterministically renders the checked-in inventory of the committed jextract MLX binding. */
public final class MlxApiInventory {

  private static final Path BINDING_DIRECTORY =
      Path.of("jmlx-ffi/src/main/generated/java/se/alipsa/jmlx/ffi");
  private static final Path MAPPING_FILE = Path.of("req/mlx-api-inventory-overrides.json");
  private static final Pattern PIN = Pattern.compile("(?m)^([A-Z_]+)=\"([^\"]+)\"$");
  private static final Pattern METHOD =
      Pattern.compile("(?m)^    public static [^\\n(]+ (_?mlx_[a-z0-9_]+)\\(");
  private static final Pattern DOWNCALL_HOLDER =
      Pattern.compile("(?m)^    private static class (_?mlx_[a-z0-9_]+) \\{");
  private static final Pattern VARIADIC_INVOKER =
      Pattern.compile(
          "(?ms)^    public static class (_?mlx_[a-z0-9_]+) \\{.*?^        public static \\1"
              + " makeInvoker\\(MemoryLayout\\.\\.\\. layouts\\)");
  private static final Pattern VARIADIC_INVOKER_CANDIDATE =
      Pattern.compile("(?m)^    public static class (_?mlx_[a-z0-9_]+) \\{");
  private static final Pattern CONSTANT =
      Pattern.compile("(?m)^    public static int (MLX_[A-Z0-9_]+)\\(\\)");

  // CLAUDE.md documents that an unfiltered jextract run silently drops exactly these four
  // mlx_array constructor/destructor symbols with no warning. The variadic classes also have a
  // different generated shape from ordinary holders. Check all six by name so either shape change
  // cannot silently remove them from the inventory.
  private static final Set<String> REQUIRED_SYMBOLS =
      Set.of("mlx_array_new", "mlx_array_free", "mlx_array_new_data", "mlx_array_new_data_managed");
  private static final Set<String> VARIADIC_INVOKER_CANARIES =
      Set.of("_mlx_error", "mlx_node_namer_new");
  private static final Set<String> STATUSES =
      Set.of(
          "unplanned",
          "planned",
          "implemented",
          "unsupported-by-runtime",
          "derived-java-api",
          "internal/unstable-upstream");

  private MlxApiInventory() {}

  /** Returns the complete checked-in inventory text for {@code repositoryRoot}. */
  public static String render(Path repositoryRoot) throws IOException {
    List<Entry> entries = discover(repositoryRoot);
    Map<String, Mapping> mappings = readMappings(repositoryRoot.resolve(MAPPING_FILE));
    validateMappings(repositoryRoot, entries, mappings);

    StringBuilder out = new StringBuilder();
    out.append("# MLX API inventory\n\n");
    out.append("Generated by `./gradlew generateMlxApiInventory`; do not edit manually.\n\n");
    out.append("This inventory covers committed generated `mlx_h` downcalls and constants, plus\n");
    out.append(
        "generated layout/accessor types and upcall interfaces. An auto-rendered `unplanned`\n");
    out.append("row is reporting only: handwritten use requires an explicit mapping record.\n\n");
    String bootstrap =
        Files.readString(
            repositoryRoot.resolve("scripts/bootstrap-native.sh"), StandardCharsets.UTF_8);
    out.append("- mlx-metal: `").append(pin(bootstrap, "MLX_METAL_VERSION")).append("`\n");
    out.append("- mlx-c: `").append(pin(bootstrap, "MLX_C_COMMIT")).append("`\n");
    appendTotals(out, entries, mappings);
    out.append(
        "\n| Generated binding | Category | Status | Facade / reason | Tests | Probe | Scope |\n");
    out.append("| --- | --- | --- | --- | --- | --- | --- |\n");
    for (Entry entry : entries) {
      Mapping mapping = mappings.get(entry.identity());
      out.append("| `").append(entry.identity()).append("` | ").append(entry.category().label());
      out.append(" | ").append(mapping == null ? "unplanned" : mapping.status());
      out.append(" | ").append(mapping == null ? "—" : markdown(mapping.facadeOrReason()));
      out.append(" | ").append(mapping == null ? "—" : markdown(mapping.tests()));
      out.append(" | ").append(mapping == null ? "—" : markdown(mapping.probe()));
      out.append(" | ").append(mapping == null ? "—" : markdown(mapping.scope())).append(" |\n");
    }
    return out.toString();
  }

  /** Writes the rendered inventory to {@code output}. */
  public static void write(Path repositoryRoot, Path output) throws IOException {
    Files.writeString(output, render(repositoryRoot), StandardCharsets.UTF_8);
  }

  /** Returns the data needed by the handwritten-source guard from one discovery/mapping pass. */
  static GuardData guardData(Path repositoryRoot) throws IOException {
    List<Entry> entries = discover(repositoryRoot);
    Map<String, Mapping> mappings = readMappings(repositoryRoot.resolve(MAPPING_FILE));
    validateMappings(repositoryRoot, entries, mappings);
    Set<String> types = new TreeSet<>();
    for (Entry entry : entries) {
      if (entry.category() == Category.LAYOUT || entry.category() == Category.UPCALL) {
        types.add(entry.identity());
      }
    }
    Map<String, Set<String>> sources = new HashMap<>();
    for (Mapping mapping : mappings.values()) {
      sources.put(mapping.binding(), mapping.sources());
    }
    Set<String> observedUseRequired = new TreeSet<>();
    for (Mapping mapping : mappings.values()) {
      if (mapping.status().equals("implemented")
          || (mapping.status().equals("planned") && !mapping.sources().isEmpty())) {
        observedUseRequired.add(mapping.binding());
      }
    }
    return new GuardData(Map.copyOf(sources), Set.copyOf(types), Set.copyOf(observedUseRequired));
  }

  private static List<Entry> discover(Path repositoryRoot) throws IOException {
    Path directory = repositoryRoot.resolve(BINDING_DIRECTORY);
    String binding = Files.readString(directory.resolve("mlx_h.java"), StandardCharsets.UTF_8);
    Set<String> symbols = matches(binding, METHOD);
    Set<String> variadicInvokers = matches(binding, VARIADIC_INVOKER);
    int variadicCandidates = matches(binding, VARIADIC_INVOKER_CANDIDATE).size();
    symbols.addAll(variadicInvokers);
    int holders = countDowncallHolders(binding) + variadicCandidates;
    if (holders == 0
        || variadicInvokers.size() != variadicCandidates
        || symbols.size() != holders) {
      throw new IllegalStateException(
          "Only "
              + symbols.size()
              + " of "
              + holders
              + " mlx_h downcall implementations matched; expected every holder or variadic invoker"
              + " to have a public downcall. The generated binding layout or inventory parser may"
              + " have changed.");
    }
    Set<String> missingRequired = new TreeSet<>(REQUIRED_SYMBOLS);
    missingRequired.removeAll(symbols);
    if (!missingRequired.isEmpty()) {
      throw new IllegalStateException(
          "Expected callable mlx_h bindings missing from the inventory: "
              + missingRequired
              + ". The generated binding layout or inventory parser may have changed.");
    }
    Set<String> missingVariadicCanaries = new TreeSet<>(VARIADIC_INVOKER_CANARIES);
    missingVariadicCanaries.removeAll(symbols);
    if (!missingVariadicCanaries.isEmpty()) {
      throw new IllegalStateException(
          "Expected variadic invoker canary bindings missing from the inventory: "
              + missingVariadicCanaries
              + ". The upstream header may have removed them, or the generated invoker shape may"
              + " have changed.");
    }
    TreeSet<Entry> entries = new TreeSet<>(Comparator.comparing(Entry::identity));
    for (String symbol : symbols) {
      entries.add(new Entry("mlx_h." + symbol, Category.DOWNCALL));
    }
    for (String constant : matches(binding, CONSTANT)) {
      entries.add(new Entry("mlx_h." + constant, Category.CONSTANT));
    }
    try (Stream<Path> files = Files.list(directory)) {
      files
          .filter(path -> path.getFileName().toString().endsWith(".java"))
          .map(path -> path.getFileName().toString().replaceFirst("\\.java$", ""))
          .filter(name -> !name.equals("mlx_h"))
          .forEach(
              name -> {
                if (name.equals("mlx_h$shared")) {
                  entries.add(new Entry(name, Category.INFRASTRUCTURE));
                } else if (name.contains("$fun")
                    || name.contains("$dtor")
                    || name.equals("mlx_error_handler_func")) {
                  entries.add(new Entry(name, Category.UPCALL));
                } else {
                  entries.add(new Entry(name, Category.LAYOUT));
                }
              });
    }
    return List.copyOf(entries);
  }

  private static Set<String> matches(String source, Pattern pattern) {
    Set<String> matches = new TreeSet<>();
    Matcher matcher = pattern.matcher(source);
    while (matcher.find()) {
      matches.add(matcher.group(1));
    }
    return matches;
  }

  private static Map<String, Mapping> readMappings(Path mappingFile) throws IOException {
    if (!Files.isRegularFile(mappingFile)) {
      throw new IllegalArgumentException("Missing required inventory mapping file: " + mappingFile);
    }
    try {
      Object root = new JsonParser(Files.readString(mappingFile, StandardCharsets.UTF_8)).parse();
      if (!(root instanceof Map<?, ?> rootObject) || rootObject.size() != 1) {
        throw new IllegalArgumentException(
            "Inventory mapping must be a JSON object containing only 'records'");
      }
      Object records = rootObject.get("records");
      if (!(records instanceof List<?> recordList)) {
        throw new IllegalArgumentException("Inventory mapping field 'records' must be an array");
      }
      Map<String, Mapping> mappings = new HashMap<>();
      for (int index = 0; index < recordList.size(); index++) {
        Object record = recordList.get(index);
        if (!(record instanceof Map<?, ?> object)) {
          throw new IllegalArgumentException(
              "Inventory mapping record at index "
                  + index
                  + " must be an object; found "
                  + String.valueOf(record));
        }
        for (Mapping mapping : Mapping.from(object, index)) {
          if (mappings.put(mapping.binding(), mapping) != null) {
            throw new IllegalArgumentException(
                "Duplicate inventory mapping record: " + mapping.binding());
          }
        }
      }
      return mappings;
    } catch (IllegalArgumentException exception) {
      throw new IllegalArgumentException(
          "Invalid inventory mapping file " + mappingFile + ": " + exception.getMessage(),
          exception);
    }
  }

  private static void validateMappings(
      Path repositoryRoot, List<Entry> entries, Map<String, Mapping> mappings) {
    Map<String, Category> known = new HashMap<>();
    for (Entry entry : entries) {
      known.put(entry.identity(), entry.category());
    }
    for (Mapping mapping : mappings.values()) {
      Category category = known.get(mapping.binding());
      if (category == null) {
        throw new IllegalArgumentException(
            "Unknown or stale inventory mapping: " + mapping.binding());
      }
      if (category != mapping.category()) {
        throw new IllegalArgumentException(
            "Inventory mapping category for "
                + mapping.binding()
                + " is "
                + mapping.category().label()
                + ", but generated binding is "
                + category.label());
      }
      for (String source : mapping.sources()) {
        if (!Files.isRegularFile(repositoryRoot.resolve(source))) {
          throw new IllegalArgumentException("Stale inventory mapping source path: " + source);
        }
      }
    }
  }

  private static void appendTotals(
      StringBuilder out, List<Entry> entries, Map<String, Mapping> mappings) {
    Map<Category, Integer> categoryCounts = new EnumMap<>(Category.class);
    Map<String, Integer> statusCounts = new TreeMap<>();
    for (Entry entry : entries) {
      categoryCounts.merge(entry.category(), 1, Integer::sum);
      String status =
          mappings.containsKey(entry.identity())
              ? mappings.get(entry.identity()).status()
              : "unplanned";
      statusCounts.merge(status, 1, Integer::sum);
    }
    out.append("- generated entries: ").append(entries.size()).append("\n");
    out.append("- by category: ");
    appendCounts(
        out,
        categoryCounts.entrySet().stream()
            .map(entry -> entry.getKey().label() + "=" + entry.getValue())
            .toList());
    out.append("\n- by status: ");
    appendCounts(
        out,
        statusCounts.entrySet().stream()
            .map(entry -> entry.getKey() + "=" + entry.getValue())
            .toList());
    out.append("\n");
  }

  private static void appendCounts(StringBuilder out, List<String> counts) {
    for (int i = 0; i < counts.size(); i++) {
      if (i > 0) {
        out.append(", ");
      }
      out.append(counts.get(i));
    }
  }

  private static String markdown(String value) {
    return value == null || value.isEmpty() ? "—" : value.replace("|", "\\|");
  }

  private static String pin(String bootstrap, String name) {
    Matcher matcher = PIN.matcher(bootstrap);
    while (matcher.find()) {
      if (matcher.group(1).equals(name)) {
        return matcher.group(2);
      }
    }
    throw new IllegalArgumentException("scripts/bootstrap-native.sh does not define " + name);
  }

  private static int countDowncallHolders(String binding) {
    return matches(binding, DOWNCALL_HOLDER).size();
  }

  private enum Category {
    DOWNCALL("downcall"),
    CONSTANT("constant"),
    LAYOUT("layout/accessor"),
    UPCALL("upcall interface"),
    INFRASTRUCTURE("jextract infrastructure");

    private final String label;

    Category(String label) {
      this.label = label;
    }

    String label() {
      return label;
    }

    static Category required(String value) {
      for (Category category : values()) {
        if (category.label.equals(value)) {
          return category;
        }
      }
      throw new IllegalArgumentException("Unknown inventory category: " + value);
    }
  }

  private record Entry(String identity, Category category) {}

  record GuardData(
      Map<String, Set<String>> mappingSources,
      Set<String> generatedTypes,
      Set<String> observedUseRequired) {}

  private record Mapping(
      String binding,
      Category category,
      String status,
      String facadeOrReason,
      String tests,
      String probe,
      Set<String> sources) {
    static List<Mapping> from(Map<?, ?> object, int index) {
      String context = context(object, index);
      Set<String> allowed =
          Set.of(
              "binding",
              "bindings",
              "category",
              "status",
              "facadeOrReason",
              "tests",
              "probe",
              "sources");
      for (Object field : object.keySet()) {
        if (!(field instanceof String name) || !allowed.contains(name)) {
          throw new IllegalArgumentException(
              context + " contains an unknown field: '" + String.valueOf(field) + "'");
        }
      }
      List<String> bindings = bindings(object, context);
      String categoryValue = required(object, "category", context);
      Category category;
      try {
        category = Category.required(categoryValue);
      } catch (IllegalArgumentException exception) {
        throw new IllegalArgumentException(
            context + " has an unknown 'category' value: '" + categoryValue + "'", exception);
      }
      String status = required(object, "status", context);
      if (!STATUSES.contains(status) || status.equals("unplanned")) {
        throw new IllegalArgumentException(
            context + " has an invalid explicit 'status' value: '" + status + "'");
      }
      List<Mapping> mappings = new ArrayList<>();
      for (String binding : bindings) {
        mappings.add(
            new Mapping(
                binding,
                category,
                status,
                required(object, "facadeOrReason", context),
                required(object, "tests", context),
                optional(object, "probe", context),
                sources(object, context)));
      }
      return mappings;
    }

    String scope() {
      return sources.isEmpty() ? "all handwritten source" : String.join("<br>", sources);
    }

    private static List<String> bindings(Map<?, ?> object, String context) {
      boolean hasBinding = object.containsKey("binding");
      boolean hasBindings = object.containsKey("bindings");
      if (hasBinding == hasBindings) {
        throw new IllegalArgumentException(
            context + " requires exactly one of 'binding' or 'bindings'");
      }
      if (hasBinding) {
        return List.of(required(object, "binding", context));
      }
      Object value = object.get("bindings");
      if (!(value instanceof List<?> values) || values.isEmpty()) {
        throw new IllegalArgumentException(
            context
                + " field 'bindings' must be a non-empty array; found "
                + String.valueOf(value));
      }
      List<String> bindings = new ArrayList<>();
      for (Object member : values) {
        if (!(member instanceof String binding) || binding.isBlank()) {
          throw new IllegalArgumentException(
              context
                  + " field 'bindings' must contain non-empty strings; found "
                  + String.valueOf(member));
        }
        bindings.add(binding);
      }
      return bindings;
    }

    private static Set<String> sources(Map<?, ?> object, String context) {
      Object value = object.get("sources");
      if (value == null) {
        return Set.of();
      }
      if (!(value instanceof List<?> values) || values.isEmpty()) {
        throw new IllegalArgumentException(
            context + " field 'sources' must be a non-empty array; found " + String.valueOf(value));
      }
      Set<String> sources = new TreeSet<>();
      for (Object member : values) {
        if (!(member instanceof String source)
            || source.isBlank()
            || source.startsWith("/")
            || source.contains("..")
            || source.contains("*")
            || source.contains("?")) {
          throw new IllegalArgumentException(
              context
                  + " field 'sources' must contain exact relative paths without wildcards; found '"
                  + String.valueOf(member)
                  + "'");
        }
        sources.add(source);
      }
      return Set.copyOf(sources);
    }

    private static String required(Map<?, ?> object, String field, String context) {
      String value = optional(object, field, context);
      if (value == null || value.isBlank()) {
        throw new IllegalArgumentException(context + " requires a non-empty '" + field + "' field");
      }
      return value;
    }

    private static String optional(Map<?, ?> object, String field, String context) {
      Object value = object.get(field);
      if (value == null) {
        return null;
      }
      if (!(value instanceof String string)) {
        throw new IllegalArgumentException(
            context + " field '" + field + "' must be a string; found " + String.valueOf(value));
      }
      return string;
    }

    private static String context(Map<?, ?> object, int index) {
      Object binding = object.get("binding");
      if (binding instanceof String value && !value.isBlank()) {
        return "Inventory mapping record at index " + index + " for '" + value + "'";
      }
      Object bindings = object.get("bindings");
      if (bindings != null) {
        return "Inventory mapping record at index " + index + " for bindings " + bindings;
      }
      return "Inventory mapping record at index " + index;
    }
  }

  /** Small strict JSON reader; buildSrc deliberately has no runtime JSON dependency. */
  private static final class JsonParser {
    private final String source;
    private int index;

    JsonParser(String source) {
      this.source = source;
    }

    Object parse() {
      Object value = value();
      whitespace();
      if (index != source.length()) {
        throw error("Unexpected trailing input");
      }
      return value;
    }

    private Object value() {
      whitespace();
      if (index == source.length()) {
        throw error("Expected JSON value");
      }
      return switch (source.charAt(index)) {
        case '{' -> object();
        case '[' -> array();
        case '"' -> string();
        default -> throw error("Expected JSON object, array, or string");
      };
    }

    private Map<String, Object> object() {
      expect('{');
      Map<String, Object> result = new HashMap<>();
      whitespace();
      if (consume('}')) {
        return result;
      }
      do {
        whitespace();
        String key = string();
        whitespace();
        expect(':');
        if (result.put(key, value()) != null) {
          throw error("Duplicate JSON object key: " + key);
        }
        whitespace();
      } while (consume(','));
      expect('}');
      return result;
    }

    private List<Object> array() {
      expect('[');
      List<Object> result = new ArrayList<>();
      whitespace();
      if (consume(']')) {
        return result;
      }
      do {
        result.add(value());
        whitespace();
      } while (consume(','));
      expect(']');
      return result;
    }

    private String string() {
      expect('"');
      StringBuilder result = new StringBuilder();
      while (index < source.length() && source.charAt(index) != '"') {
        char character = source.charAt(index++);
        if (character == '\\') {
          if (index == source.length()) {
            throw error("Unterminated escape");
          }
          character = source.charAt(index++);
          if (character != '"' && character != '\\' && character != '/') {
            throw error("Only JSON quote, slash, and backslash escapes are supported");
          }
        }
        result.append(character);
      }
      expect('"');
      return result.toString();
    }

    private void whitespace() {
      while (index < source.length() && Character.isWhitespace(source.charAt(index))) {
        index++;
      }
    }

    private boolean consume(char expected) {
      if (index < source.length() && source.charAt(index) == expected) {
        index++;
        return true;
      }
      return false;
    }

    private void expect(char expected) {
      if (!consume(expected)) {
        throw error("Expected '" + expected + "'");
      }
    }

    private IllegalArgumentException error(String message) {
      return new IllegalArgumentException(message + " at character " + index);
    }
  }
}
