package se.alipsa.jmlx.buildsrc;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Comparator;
import java.util.HexFormat;
import java.util.List;
import java.util.Map;
import java.util.Properties;
import java.util.Set;
import java.util.TreeMap;
import java.util.TreeSet;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Stream;

/** Renders native-only evidence comparing staged public mlx-c headers with generated bindings. */
public final class MlxApiHeaderCoverage {

  private static final Pattern COMMENTS = Pattern.compile("(?s)/\\*.*?\\*/|//[^\\n]*");
  private static final Pattern FUNCTION = Pattern.compile("\\b(_?mlx_[a-z0-9_]+)\\s*\\(");
  private static final Pattern ENUM =
      Pattern.compile(
          "(?s)\\btypedef\\s+enum\\s+(mlx_[a-z0-9_]+)\\s*\\{(.*?)\\}\\s*(mlx_[a-z0-9_]+)\\s*;");
  private static final Pattern ENUM_CONSTANT = Pattern.compile("\\b(MLX_[A-Z0-9_]+)\\b");
  private static final Pattern TAGGED_TYPE =
      Pattern.compile(
          "(?s)\\btypedef\\s+(?:struct|enum)\\s+(mlx_[a-z0-9_]+)\\s*\\{.*?\\}\\s*"
              + "(mlx_[a-z0-9_]+)\\s*;");
  private static final Pattern SIMPLE_TYPEDEF_ALIAS =
      Pattern.compile("\\btypedef\\b[^;{}]*\\b(mlx_[a-z0-9_]+)\\s*;");
  private static final Pattern FUNCTION_POINTER_TYPE =
      Pattern.compile(
          "(?s)\\btypedef\\s+[^;]*?\\(\\s*\\*\\s*(mlx_[a-z0-9_]+)\\s*\\)\\s*\\([^;]*?\\)\\s*;");

  private MlxApiHeaderCoverage() {}

  /** Returns the deterministic Markdown report for staged public headers. */
  public static String render(Path repositoryRoot, Path headerDirectory, Path nativePinFile)
      throws IOException {
    validateNativePins(repositoryRoot, nativePinFile);
    List<Path> headers = headers(headerDirectory);
    Map<String, HeaderDeclaration> declared = declarations(headerDirectory, headers);
    Map<String, String> generated =
        new TreeMap<>(MlxApiInventory.generatedBindingCategories(repositoryRoot));
    generated.remove("mlx_h$shared");

    Set<String> declaredIdentities = declared.keySet();
    Set<String> generatedIdentities = generated.keySet();
    final Set<String> matched = intersection(declaredIdentities, generatedIdentities);
    final Set<String> declaredOnly = difference(declaredIdentities, generatedIdentities);
    final Set<String> generatedOnly = difference(generatedIdentities, declaredIdentities);

    final MlxPins pins = MlxPins.read(repositoryRoot);
    StringBuilder out = new StringBuilder();
    out.append("# MLX API header coverage\n\n");
    out.append("Generated by `./gradlew generateMlxApiHeaderCoverage`; do not edit manually.\n\n");
    out.append(
        "This native-only evidence compares public staged mlx-c function, enum-constant, and"
            + " named\n");
    out.append(
        "type declarations with committed jextract identities. Mismatches are reported for"
            + " review;\n");
    out.append("they do not assert that every header declaration belongs in the Java facade.\n\n");
    out.append("- mlx-metal: `").append(pins.required("MLX_METAL_VERSION")).append("`\n");
    out.append("- mlx-c: `").append(pins.required("MLX_C_COMMIT")).append("`\n");
    out.append("- public header files: ").append(headers.size()).append("\n");
    out.append("- header tree SHA-256: `")
        .append(headerDigest(headerDirectory, headers))
        .append("`\n");
    out.append("- header declarations: ").append(declared.size()).append("\n");
    out.append("- comparable generated bindings: ").append(generated.size()).append("\n");
    out.append("- declared-and-bound: ").append(matched.size()).append("\n");
    out.append("- declared-but-not-bound: ").append(declaredOnly.size()).append("\n");
    out.append("- bound-without-header-match: ").append(generatedOnly.size()).append("\n\n");

    appendSummary(out, declared, generated, matched, declaredOnly, generatedOnly);
    appendDeclaredOnly(out, declaredOnly, declared);
    appendGeneratedOnly(out, generatedOnly, generated);
    return out.toString();
  }

  /** Writes the deterministic Markdown report for staged public headers. */
  public static void write(
      Path repositoryRoot, Path headerDirectory, Path nativePinFile, Path output)
      throws IOException {
    Files.writeString(
        output, render(repositoryRoot, headerDirectory, nativePinFile), StandardCharsets.UTF_8);
  }

  private static List<Path> headers(Path headerDirectory) throws IOException {
    if (!Files.isDirectory(headerDirectory)) {
      throw new IllegalArgumentException(
          "Staged mlx-c headers are missing; run ./scripts/bootstrap-native.sh: "
              + headerDirectory);
    }
    try (Stream<Path> files = Files.walk(headerDirectory)) {
      List<Path> headers =
          files
              .filter(Files::isRegularFile)
              .filter(path -> path.getFileName().toString().endsWith(".h"))
              .sorted(
                  Comparator.comparing(
                      path -> headerDirectory.relativize(path).toString().replace('\\', '/')))
              .toList();
      if (headers.isEmpty()) {
        throw new IllegalArgumentException(
            "No public mlx-c headers found under " + headerDirectory);
      }
      return headers;
    }
  }

  private static Map<String, HeaderDeclaration> declarations(
      Path headerDirectory, List<Path> headers) throws IOException {
    Map<String, HeaderDeclaration> declarations = new TreeMap<>();
    for (Path header : headers) {
      String source = stripPreprocessor(COMMENTS.matcher(Files.readString(header)).replaceAll(" "));
      String relative = headerDirectory.relativize(header).toString().replace('\\', '/');
      addMatches(declarations, source, FUNCTION, "function", relative, true);
      addTaggedTypes(declarations, source, relative);
      addMatches(declarations, source, SIMPLE_TYPEDEF_ALIAS, "named type", relative, false);
      addMatches(declarations, source, FUNCTION_POINTER_TYPE, "named type", relative, false);
      Matcher enums = ENUM.matcher(source);
      while (enums.find()) {
        addMatches(declarations, enums.group(2), ENUM_CONSTANT, "enum constant", relative, true);
      }
    }
    return Map.copyOf(declarations);
  }

  private static void addTaggedTypes(
      Map<String, HeaderDeclaration> declarations, String source, String header) {
    Matcher matcher = TAGGED_TYPE.matcher(source);
    while (matcher.find()) {
      for (int group = 1; group <= 2; group++) {
        String identity = matcher.group(group);
        HeaderDeclaration prior =
            declarations.putIfAbsent(identity, new HeaderDeclaration("named type", header));
        if (prior != null && !prior.kind().equals("named type")) {
          throw new IllegalStateException(
              "Header identity "
                  + identity
                  + " was discovered as both "
                  + prior.kind()
                  + " and named type");
        }
      }
    }
  }

  private static void addMatches(
      Map<String, HeaderDeclaration> declarations,
      String source,
      Pattern pattern,
      String kind,
      String header,
      boolean mlxHMember) {
    Matcher matcher = pattern.matcher(source);
    while (matcher.find()) {
      String name = matcher.group(1);
      String identity = mlxHMember ? "mlx_h." + name : name;
      HeaderDeclaration prior =
          declarations.putIfAbsent(identity, new HeaderDeclaration(kind, header));
      if (prior != null && !prior.kind().equals(kind)) {
        throw new IllegalStateException(
            "Header identity "
                + identity
                + " was discovered as both "
                + prior.kind()
                + " and "
                + kind);
      }
    }
  }

  private static String stripPreprocessor(String source) {
    StringBuilder result = new StringBuilder();
    boolean continuation = false;
    for (String line : source.split("\\R", -1)) {
      boolean directive = continuation || line.stripLeading().startsWith("#");
      continuation = directive && line.stripTrailing().endsWith("\\");
      result.append(directive ? "" : line).append('\n');
    }
    return result.toString();
  }

  private static void validateNativePins(Path repositoryRoot, Path nativePinFile)
      throws IOException {
    if (!Files.isRegularFile(nativePinFile)) {
      throw new IllegalArgumentException(
          "Staged native pin marker is missing; run ./scripts/bootstrap-native.sh: "
              + nativePinFile);
    }
    Properties staged = new Properties();
    try (InputStream input = Files.newInputStream(nativePinFile)) {
      staged.load(input);
    }
    MlxPins expected = MlxPins.read(repositoryRoot);
    requirePin(staged, "mlxMetalVersion", expected.required("MLX_METAL_VERSION"));
    requirePin(staged, "mlxcCommit", expected.required("MLX_C_COMMIT"));
  }

  private static void requirePin(Properties staged, String name, String expected) {
    String actual = staged.getProperty(name);
    if (!expected.equals(actual)) {
      throw new IllegalArgumentException(
          "Staged native pin " + name + " mismatch: expected " + expected + ", found " + actual);
    }
  }

  private static String headerDigest(Path headerDirectory, List<Path> headers) throws IOException {
    try {
      MessageDigest digest = MessageDigest.getInstance("SHA-256");
      for (Path header : headers) {
        digest.update(
            headerDirectory.relativize(header).toString().getBytes(StandardCharsets.UTF_8));
        digest.update((byte) 0);
        digest.update(Files.readAllBytes(header));
        digest.update((byte) 0);
      }
      return HexFormat.of().formatHex(digest.digest());
    } catch (NoSuchAlgorithmException exception) {
      throw new IllegalStateException("SHA-256 is unavailable", exception);
    }
  }

  private static void appendSummary(
      StringBuilder out,
      Map<String, HeaderDeclaration> declared,
      Map<String, String> generated,
      Set<String> matched,
      Set<String> declaredOnly,
      Set<String> generatedOnly) {
    out.append("## Summary by declaration kind\n\n");
    out.append(
        "| Kind | Declared | Declared and bound | Declared but not bound | Bound without header"
            + " match |\n");
    out.append("| --- | ---: | ---: | ---: | ---: |\n");
    for (String kind : List.of("function", "enum constant", "named type")) {
      long declaredCount =
          declared.values().stream().filter(value -> value.kind().equals(kind)).count();
      long matchedCount =
          matched.stream().filter(identity -> declared.get(identity).kind().equals(kind)).count();
      long declaredOnlyCount =
          declaredOnly.stream()
              .filter(identity -> declared.get(identity).kind().equals(kind))
              .count();
      long generatedOnlyCount =
          generatedOnly.stream()
              .filter(identity -> generatedKind(generated.get(identity)).equals(kind))
              .count();
      out.append("| ")
          .append(kind)
          .append(" | ")
          .append(declaredCount)
          .append(" | ")
          .append(matchedCount)
          .append(" | ")
          .append(declaredOnlyCount)
          .append(" | ")
          .append(generatedOnlyCount)
          .append(" |\n");
    }
    out.append('\n');
  }

  private static String generatedKind(String category) {
    return switch (category) {
      case "downcall" -> "function";
      case "constant" -> "enum constant";
      default -> "named type";
    };
  }

  private static void appendDeclaredOnly(
      StringBuilder out, Set<String> declaredOnly, Map<String, HeaderDeclaration> declared) {
    out.append("## Declared but not bound\n\n");
    out.append(
        "The current differences include enum type identities flattened into `mlx_h` constants,"
            + " the native complex scalar carrier, and bfloat16 accessors omitted by the documented"
            + " jextract header override.\n\n");
    out.append("| Header identity | Kind | Header |\n");
    out.append("| --- | --- | --- |\n");
    for (String identity : declaredOnly) {
      HeaderDeclaration declaration = declared.get(identity);
      out.append("| `")
          .append(identity)
          .append("` | ")
          .append(declaration.kind())
          .append(" | `")
          .append(declaration.header())
          .append("` |\n");
    }
    if (declaredOnly.isEmpty()) {
      out.append("| — | — | — |\n");
    }
    out.append('\n');
  }

  private static void appendGeneratedOnly(
      StringBuilder out, Set<String> generatedOnly, Map<String, String> generated) {
    out.append("## Bound without header match\n\n");
    out.append(
        "Anonymous callback adapters generated from function parameters have no stable named C"
            + " declaration and are expected here.\n\n");
    out.append("| Generated identity | Binding category |\n");
    out.append("| --- | --- |\n");
    for (String identity : generatedOnly) {
      out.append("| `")
          .append(identity)
          .append("` | ")
          .append(generated.get(identity))
          .append(" |\n");
    }
    if (generatedOnly.isEmpty()) {
      out.append("| — | — |\n");
    }
  }

  private static Set<String> intersection(Set<String> left, Set<String> right) {
    Set<String> result = new TreeSet<>(left);
    result.retainAll(right);
    return result;
  }

  private static Set<String> difference(Set<String> left, Set<String> right) {
    Set<String> result = new TreeSet<>(left);
    result.removeAll(right);
    return result;
  }

  private record HeaderDeclaration(String kind, String header) {}
}
