package se.alipsa.jmlx.models;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.List;

/**
 * The deterministic fixture specification of the exact-bit recorder/comparator.
 *
 * <p>Every constant here feeds the capture schedule. Per-family prompt IDs, decode-step tokens and
 * the resulting batch valid lengths come from the family's committed golden JSON, which is covered
 * by the per-variant input SHA-256 hashes in parallel; {@link #sha256()} covers everything that is
 * defined here instead. Changing any constant changes the spec hash and invalidates the recordings.
 */
final class ExactBitsSpec {

  /** Every committed Tier-A decoder family under tools/hf-reference/goldens/checkpoints. */
  static final List<String> FAMILIES =
      List.of("llama", "llama31", "mistral", "mixtral", "phi3", "qwen2", "qwen3", "gemma");

  /**
   * The families whose quantized loading QuantizedDecoderTest and the README claim, derived with
   * the same group/bits/key set. Mixtral is MoE and is deliberately not in this list.
   */
  static final List<String> QUANTIZED_FAMILIES =
      List.of("llama", "qwen2", "qwen3", "mistral", "gemma", "phi3");

  static final int QUANT_GROUP = 32;
  static final int QUANT_BITS = 4;

  /** Greedy tokens generated by the direct-path and scheduler captures. */
  static final int MAX_NEW_TOKENS = 4;

  /** The shorter, deterministic second row of the 2-row left-padded batch. */
  static final int[] ROW_B = {5, 19, 2};

  /** The fill token used when left-padding the batch rows. */
  static final int PAD_FILL = 0;

  /**
   * Fixed decode tokens of the batched 1-column steps: index 0 is the per-row-B token of
   * batch-decode-0, index 1 the per-row-B token of batch-decode-1, index 2 the row-A fallback when
   * a golden has fewer decode steps than the number of batched decode steps.
   */
  static final int[] BATCH_DECODE_TOKENS_B = {7, 11, 7};

  /** The embedding hook adds {@link #HOOK_CONSTANT} to every element of row {@link #HOOK_ROW}. */
  static final int HOOK_ROW = 1;

  static final float HOOK_CONSTANT = 1e-3f;

  /** The scheduler config equals SchedulerFixtures.config(2, 2); the gate waits for n = 2. */
  static final int SCHEDULER_BATCH = 2;

  static final int SCHEDULER_QUEUED = 2;
  static final int SCHEDULER_PROMPT_BUDGET = 4096;
  static final int SCHEDULER_MAX_NEW = 256;
  static final int SCHEDULER_GATE_N = 2;
  static final int SCHEDULER_GATE_WAIT_MS = 200;

  private ExactBitsSpec() {}

  /**
   * SHA-256 of the canonical JSON encoding of this specification, so a spec change can never
   * silently compare against a recording made from a different one.
   */
  static String sha256() {
    StringBuilder canonical = new StringBuilder();
    canonical.append('{');
    canonical.append("\"families\":").append(json(FAMILIES)).append(',');
    canonical.append("\"quantizedFamilies\":").append(json(QUANTIZED_FAMILIES)).append(',');
    canonical.append("\"quantGroup\":").append(QUANT_GROUP).append(',');
    canonical.append("\"quantBits\":").append(QUANT_BITS).append(',');
    canonical.append("\"maxNewTokens\":").append(MAX_NEW_TOKENS).append(',');
    canonical.append("\"rowB\":").append(ints(ROW_B)).append(',');
    canonical.append("\"padFill\":").append(PAD_FILL).append(',');
    canonical.append("\"batchDecodeTokensB\":").append(ints(BATCH_DECODE_TOKENS_B)).append(',');
    canonical.append("\"hookRow\":").append(HOOK_ROW).append(',');
    canonical
        .append("\"hookConstantBits\":")
        .append(Float.floatToIntBits(HOOK_CONSTANT))
        .append(',');
    canonical.append("\"schedulerBatch\":").append(SCHEDULER_BATCH).append(',');
    canonical.append("\"schedulerQueued\":").append(SCHEDULER_QUEUED).append(',');
    canonical.append("\"schedulerPromptBudget\":").append(SCHEDULER_PROMPT_BUDGET).append(',');
    canonical.append("\"schedulerMaxNew\":").append(SCHEDULER_MAX_NEW).append(',');
    canonical.append("\"schedulerGateN\":").append(SCHEDULER_GATE_N).append(',');
    canonical.append("\"schedulerGateWaitMs\":").append(SCHEDULER_GATE_WAIT_MS);
    canonical.append('}');
    return sha256(canonical.toString());
  }

  static String sha256(String content) {
    return sha256(content.getBytes(StandardCharsets.UTF_8));
  }

  static String sha256(byte[] content) {
    try {
      return hex(MessageDigest.getInstance("SHA-256").digest(content));
    } catch (NoSuchAlgorithmException e) {
      throw new IllegalStateException("SHA-256 is required", e);
    }
  }

  static String hex(byte[] bytes) {
    StringBuilder out = new StringBuilder(2 * bytes.length);
    for (byte b : bytes) {
      out.append(String.format("%02x", b));
    }
    return out.toString();
  }

  private static String json(List<String> values) {
    StringBuilder out = new StringBuilder("[");
    for (int i = 0; i < values.size(); i++) {
      if (i > 0) {
        out.append(',');
      }
      out.append('"').append(values.get(i)).append('"');
    }
    return out.append(']').toString();
  }

  private static String ints(int[] values) {
    StringBuilder out = new StringBuilder("[");
    for (int i = 0; i < values.length; i++) {
      if (i > 0) {
        out.append(',');
      }
      out.append(values[i]);
    }
    return out.append(']').toString();
  }
}
